# 1. MEMBUAT PRIMARY KEY PADA MASING MASING TABLE
ALTER TABLE bank_muamalat.Customers ADD PRIMARY KEY (CustomerID) NOT ENFORCED;
ALTER TABLE bank_muamalat.Orders ADD PRIMARY KEY (OrderID) NOT ENFORCED;
ALTER TABLE bank_muamalat.Products ADD PRIMARY KEY (ProdNumber) NOT ENFORCED;
ALTER TABLE bank_muamalat.ProductCategory ADD PRIMARY KEY (CategoryID) NOT ENFORCED;